import type { Metadata } from "next"
import { Geist, Geist_Mono, Metamorphous } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const metamorphous = Metamorphous({
  variable: "--font-metamorphous",
  subsets: ["latin"],
  weight: "400",
})

// For Molle, which only comes in italic, we'll use localFont
// Since it's not in next/font/google's standard list, we'll load it via CSS variable

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* Molle font is not available in next/font/google, keeping Google Fonts link for now */}
        <link
          href="https://fonts.googleapis.com/css2?family=Molle&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${metamorphous.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
